# fly.toml app configuration file generated for server-rough-haze-1098 on 2024-11-20T10:15:10+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'server-rough-haze-1098'
primary_region = 'cdg'

[build]

[env]
  PORT = "3000"

[processes]
  app = "node index.js"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  restart_limit = 0
  method = "GET"
  timeout = "5s"
  path = "/health"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
