name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  deployment_pipeline:
    runs-on: ubuntu-latest
    env:
      CI: true
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
      PORT: ${{ secrets.PORT }}
      SECRET: ${{ secrets.SECRET }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies, lint, build and test client
        run: |
          cd client
          npm ci
          npm run lint
          npm run build
          npm run test

      - name: Install dependencies and test server
        run: |
          cd server
          npm ci
          npm run test

      - name: Install Playwright Chromium Browser
        run: npx playwright install --with-deps chromium
      - name: Run E2E tests
        run: |
          cd client
          npm run test:e2e
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: client/playwright-report
          retention-days: 30

      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy to Fly
        if: ${{ github.event_name == 'push' && !contains(github.event.head_commit.message, '#skip') }}
        run: |
          cd server
          flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  tag_release:
    runs-on: ubuntu-latest
    needs: deployment_pipeline
    if: ${{ github.event_name == 'push' && !contains(github.event.head_commit.message, '#skip') }}
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.71.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          WITH_V: true

  notify_discord_on_success:
    runs-on: ubuntu-latest
    needs: [deployment_pipeline, tag_release]
    steps:
      - uses: actions/checkout@v4
      - name: Store timestamp
        run: echo "TIMESTAMP=$(TZ='Europe/Helsinki' date +'%T')" >> $GITHUB_ENV
      - run: git fetch --prune --unshallow --tag
      - name: Get latest tag
        run: echo "LATEST_TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV
      - name: Notify Discord success
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{
                "username": "Bloglist GitHub Actions Pipeline",
                "embeds": [
                  {
                    "title": "A new version of Bloglist app has been deployed",
                    "description": "by ${{ github.actor }}. Version: ${{ env.LATEST_TAG }}",
                    "color": 65280,
                    "footer": {
                      "text": "Severity: Informational | Time: ${{ env.TIMESTAMP }}"
                    }
                  }
                ]
              }' \
            ${{ secrets.DISCORD_WEBHOOK }}

  notify_discord_on_failure:
    runs-on: ubuntu-latest
    needs: deployment_pipeline
    if: ${{ failure() && github.event_name == 'push' }}
    steps:
      - uses: actions/checkout@v4
      - name: Store timestamp
        run: echo "TIMESTAMP=$(TZ='Europe/Helsinki' date +'%T')" >> $GITHUB_ENV
      - name: Notify Discord failure
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{
                "username": "Bloglist GitHub Actions Pipeline",
                "embeds": [
                  {
                    "title": "Build failed for Bloglist app",
                    "description": "commit [${{ github.sha }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }}) by ${{ github.actor }} broke the build.",
                    "color": 16711680,
                    "footer": {
                      "text": "Severity: Error | Time: ${{ env.TIMESTAMP }}"
                    }
                  }
                ]
              }' \
            ${{ secrets.DISCORD_WEBHOOK }}